- name: Ansible Playbook to Create all the RoboShop Project Jobs in Jenkins Server.
  hosts: localhost
  roles:
    - jenkins-jobs
  vars:
    folders:
      - demo
    pipeline_jobs:
      - { jobName: sample3, folderName: "demo", repoName: "learning-jenkins"}