- name: Create Jenkins Folders
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    password: admin
    user: admin
    url: http://172.31.10.85:8080
  loop:
    - demo

- name: Create Jenkins jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/pipeline-job.xml') }}"
    name: "{{item.folderName}}/{{item.jobName}}"
    password: admin
    user: admin
    url: http://172.31.10.85:8080
  loop:
    - { jobName: "sample3", folderName: "demo" }