- name: Create Template file
  template:
    src: pipeline-job.xml
    dest: /tmp

- name: Create Jenkins jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/pipeline-job.xml') }}"
    name: "{{item.folderName}}/{{item.jobName}}"
    password: admin
    user: admin
    url: http://172.31.10.85:8080
